### ISSUE TITLE
Does not build with hasql 1.10 & co

### ISSUE THREAD

**Issue by wolfgangwalther** [diogob/postgres-websockets#113]
When I try to jailbreak it, I get something like:

```
src/PostgresWebsockets/HasqlBroadcast.hs:24:38: error: [GHC-61689]
    Module ‘Hasql.Connection’ does not export ‘ConnectionError’.
   |
24 | import Hasql.Connection (Connection, ConnectionError)
   |                                      ^^^^^^^^^^^^^^^

src/PostgresWebsockets/HasqlBroadcast.hs:26:1: error: [GHC-61948]
    Could not find module ‘Hasql.Connection.Setting’.
    Perhaps you meant
      Hasql.Connection.Settings (from hasql-1.10.3)
      Hasql.Connection.Config
    Use -v to see a list of the files searched for.
   |
26 | import qualified Hasql.Connection.Setting as HC
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/PostgresWebsockets/HasqlBroadcast.hs:27:1: error: [GHC-87110]
    Could not find module ‘Hasql.Connection.Setting.Connection’.
    Use -v to see a list of the files searched for.
   |
27 | import qualified Hasql.Connection.Setting.Connection as HC
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by diogob** [comment]
@wolfgangwalther thanks for reporting! I just uploaded the [0.12.1.0 version](https://hackage.haskell.org/package/postgres-websockets) that should compile.
