### ISSUE TITLE
Currently fails to build with hasql 1.9 / hasql-pool 1.3

### ISSUE THREAD

**Issue by wolfgangwalther** [diogob/postgres-websockets#108]
Bounds error here: https://hydra.nixos.org/build/305721506/nixlog/1

When I do try to build despite the too strict bounds, I get:

```
src/PostgresWebsockets/HasqlBroadcast.hs:43:3: error: [8;;https://errors.haskell.org/messages/GHC-83865GHC-838658;;]
    • Couldn't match type ‘[Hasql.Connection.Setting.Setting]’
                     with ‘ByteString’
      Expected: ByteString -> IO (Either ConnectionError Connection)
        Actual: [Hasql.Connection.Setting.Setting]
                -> IO (Either ConnectionError Connection)
    • In the first argument of ‘(>=>)’, namely ‘acquire’
      In the expression:
        acquire
          >=>
            (sequence
               . mapBoth showBS (newHasqlBroadcasterForConnection . return))
      In an equation for ‘newHasqlBroadcasterOrError’:
          newHasqlBroadcasterOrError onConnectionFailure ch
            = acquire
                >=>
                  (sequence
                     . mapBoth showBS (newHasqlBroadcasterForConnection . return))
            where
                newHasqlBroadcasterForConnection
                  = newHasqlBroadcasterForChannel onConnectionFailure ch Nothing
   |
43 |   acquire >=> (sequence . mapBoth showBS (newHasqlBroadcasterForConnection . return))
   |   ^^^^^^^

src/PostgresWebsockets/HasqlBroadcast.hs:49:60: error: [8;;https://errors.haskell.org/messages/GHC-83865GHC-838658;;]
    • Couldn't match type ‘[Hasql.Connection.Setting.Setting]’
                     with ‘ByteString’
      Expected: ByteString -> IO (Either ConnectionError Connection)
        Actual: [Hasql.Connection.Setting.Setting]
                -> IO (Either ConnectionError Connection)
    • In the second argument of ‘(.)’, namely ‘retryConnection’
      In the expression:
        fmap (either (panic "Failure on connection retry") id)
          . retryConnection
      In an equation for ‘tryUntilConnected’:
          tryUntilConnected maxRetries
            = fmap (either (panic "Failure on connection retry") id)
                . retryConnection
            where
                retryConnection conStr
                  = retrying retryPolicy shouldRetry (const $ acquire conStr)
                maxDelayInMicroseconds = 32000000
                firstDelayInMicroseconds = 1000000
                retryPolicy
                  = capDelay maxDelayInMicroseconds
                      $ exponentialBackoff firstDelayInMicroseconds
                ....
   |
49 |   fmap (either (panic "Failure on connection retry") id) . retryConnection
   |    
```

Have not investigated further, yet.
